"use client";
// import type { Metadata } from "next";
import { usePathname } from "next/navigation";
import { Inter } from "next/font/google";
import "./globals.css";
import { BottomBar, Sidebar } from "@/components/Sidebar";
import NavBar from "@/components/NavBar";
import TopBar from "@/components/TopBar";
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "./context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isLoginPage = pathname === "/login";
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div
            className={`${
              !isLoginPage && "flex flex-col md:flex-row h-screen"
            }`}
          >
            {!isLoginPage ? <Sidebar /> : <NavBar />}
            <div className="flex-grow">
              {!isLoginPage && <TopBar />}
              <main className={`px-8 py-8 ${!isLoginPage && "md:ml-[18rem]"}`}>
                {children}
              </main>
            </div>
            {!isLoginPage && <BottomBar />}
            <Toaster />
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
